name: Tests

on: [push]

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test_with_Selenoid
    steps:
    
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
       python-version: '3.x'
       architecture  : 'x64'
    
    - name: Install PyTest
      run : |
       python -m pip install --upgrade pip
       pip install flake8 pytest
    
    - name: Install Selenium
      run : |
       python -m pip install selenium
    
    - name: Run test
      run: pytest test.py

