name: WDIO Tests

on: [push]

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test SELENOID JOB
    steps:
    - uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - name: Start cit
      run: npm ci
        
      
    - name: Test with pytest
      run: |
        pytest test.py

    
