name: Regression-Tests

on: [push]

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test_with_Selenoid
    steps:
    
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
       python-version: '3.8'
       architecture  : 'x64'
    
    - name: Install PyTest
      run : |
       python -m pip install --upgrade pip
       pip install flake8 pytest
    
    - name: Install Selenium
      run : |
       python -m pip install selenium
       
    
    - name: Install Allure
      run : |
       pip install allure-pytest
       
    - name: Run tests
      run : |
       python test.py
       
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8   
    
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
        #id: allure-report
      with:
        allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
        allure_history: allure-history
           
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-report
        path: ./allure-report
    
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs
       
      
       
   
     
     
      
