name: WDIO tests

on: [push]
      

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
    - name: Start Selenoid Server
    - uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
          
    - run : npm cit  
    - name: run test
    - run : npm test
    
