name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -U pytest selenium flake8 pylint allure-pytest

    - name: Check out and download repository
      uses: actions/checkout@v2

    - name: Check code
      run: |
        flake8 --exit-zero Tests/**
        pylint --errors-only Tests/**

    - name: Start Selenoid
      run: |
        wget --no-check-certificate -O cm https://github.com/aerokube/cm/releases/latest/download/cm_linux_amd64
        chmod +x cm
        ./cm selenoid start --browsers 'firefox;chrome;opera' --last-versions 1
        curl http://localhost:4444/status

    - name: Run tests Firefox
      run: |
        pytest --alluredir=allure-results --browser_name=firefox Tests/**
      continue-on-error: true

    - name: Generate Allure report
      uses: afiore/action-allure-report@v0.1.0
      if: always()
      id: allure-report
      with:      
        results-dir: allure-results
        report-dir: allure-report
    
    - name: Run tests Chrome
      run: |
        pytest --alluredir=allure-results --browser_name=chrome Tests/**
      continue-on-error: true
    
    - name: Generate Allure report
      uses: afiore/action-allure-report@v0.1.0
      if: always()
      id: allure-report
      with:      
        results-dir: allure-results
        report-dir: allure-report

    - name: Run tests Opera
      run: |
        pytest --alluredir=allure-results --browser_name=opera Tests/**
      continue-on-error: true
      
    - name: Generate Allure report
      uses: afiore/action-allure-report@v0.1.0
      if: always()
      id: allure-report
      with:      
        results-dir: allure-results
        report-dir: allure-report
        
    - name: Deploy report to Github
      uses: actions/upload-artifact@v2.1.3
      if: always()
      with:
        name: allure-report
        path: ./allure-report

    