name: WDIO Tests

on: [push]

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test SELENOID JOB
    steps:
    - uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - name: Start cit
      run: npm ci     
    

    - uses: actions/setup-python@v1
      with:
       python-version: '3.8'
       architecture: 'x64'
    - name: Install dependencies
       run:|
         python -m pip install --upgrade pip
         pip install flake8 pytest
    
    
    - name: Run tests
      run: coverage run src/test.py
    - name: Test with pytest
      run: python -c "import sys; print(sys.version)"
