name: Regression-Tests

on: [push]

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test_with_Selenoid
    steps:
    - uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
        
    

    - uses: actions/setup-python@v1
      with:
       python-version: '3.8'
       architecture  : 'x64'
    - name: Install PyTest
      run : |
       python -m pip install --upgrade pip
       pip install flake8 pytest
    - name: Install Selenium
      run : |
       python -m pip install selenium
       
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        
        pushd allure-pytest
        python setup.py sdist bdist_wheel
        twine upload dist/*
        popd
        
     
    
    - name: Run tests
      run : python test.py

  
