name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -U pytest selenium flake8 pylint allure-pytest

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8


    - name: Check out and download repository
      uses: actions/checkout@v2

    - name: Check code
      run: |
        flake8 --exit-zero Tests/**
        pylint --errors-only Tests/**

    - name: Start Selenoid
      run: |
        wget --no-check-certificate -O cm https://github.com/aerokube/cm/releases/latest/download/cm_linux_amd64
        chmod +x cm
        ./cm selenoid start --browsers 'firefox;chrome;opera' --last-versions 1
        curl http://localhost:4444/status

    - name: Run tests Firefox
      run: |
        pytest --alluredir=allure-results --browser_name=firefox Tests/test_main.py
        
      continue-on-error: true
    
    - name: Run tests Chrome
      run: |
        pytest --browser_name=chrome Tests/test_main.py
      continue-on-error: true
    
    - name: Run tests Opera
      run: |
        pytest --browser_name=opera Tests/test_main.py
      continue-on-error: true

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@v1.3
      if: always()
      id: allure-report      
      with:
        allure_results: build/allure-results
        allure_report: allure-report
        allure_history: allure-history
        

    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results
        path: ./allure-results
